spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/masterdata
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,loggers
    endpoint:
      health:
        show-details: always
logging:
  level:
    root: INFO
